version: "3"
services:
  go:
    build: ./go
    ports:
      - 3000:3000
    container_name: worldmap-go
    tty: true
    volumes:
      - ./go:/go/app
    environment:
      - APP_PORT=3000
  nginx:
    image: nginx
    depends_on:
      - go
    container_name: worldmap-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
